server:
    port: 8081
base:
    url:
        property: http://rest-api:8080/api/customers
spring:
    application:
        name: customers-service
    cloud:
        loadbalancer:
            retry:
                enabled: false
        discovery:
            client:
                simple:
                    instances:
                        customers-service[0]:
                            uri: http://localhost:80
                        customers-service[1]:
                            uri: http://localhost:81
logging:
    level:
        org.springframework: DEBUG
        root: debug
        org.hibernate.sql: debug
        org.hibernate.type.descriptor.sql.BasicBinder: TRACE
