base:
    url:
        property: /api/customers
spring:
    datasource:
        driver-class-name: org.postgresql.Driver
        password: avarer666
        url: jdbc:postgresql://localhost:5432/customerdatabase
        username: postgres
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: update
